### ISSUE TITLE
Bug: TypeError: Cannot read property &#39;date&#39; of undefined

### ISSUE THREAD

**Issue by rdok** [i-bank/openbank-api#1]
#### Goal 
Find transaction by id.  

#### Attempt:
```
POST https://nbgdemo.azure-api.net/nodeopenapi/api/transactions/rest HTTP/1.1
Content-Type: application/json
Host: nbgdemo.azure-api.net
Content-Length: 120
Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••

{
  "nbgtrackid": "502497b6-808e-472c-9eaa-a6fb029f8648",
  "payload": {
    "id": "57251102db45021c1aebef35"
  }
}
```

#### Result
```
 <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>500</em> TypeError: Cannot read property &#39;date&#39; of undefined</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at listmore (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\implementation\transactions\implementation.ts:22:33)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:131:13)</li><li> &nbsp; &nbsp;at Route.dispatch (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\route.js:112:3)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:277:22</li><li> &nbsp; &nbsp;at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)</li><li> &nbsp; &nbsp;at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)</li><li> &nbsp; &nbsp;at router (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:46:12)</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\layer.js:95:5)</li><li> &nbsp; &nbsp;at trim_prefix (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:312:13)</li><li> &nbsp; &nbsp;at C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:280:7</li><li> &nbsp; &nbsp;at Function.process_params (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:330:12)</li><li> &nbsp; &nbsp;at next (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:271:10)</li><li> &nbsp; &nbsp;at Function.handle (C:\deploy\openapi\NbgOpenNodeApi\BankOpenNodeTsApi\OBPNodeTsApi\node_modules\express\lib\router\index.js:176:3)</li></ul>
    </div>
```

**Comment by rdok** [comment]
Ping @faniskou

**Comment by faniskou** [comment]
Thanks for the notice. We have plan to release a version with many fixes
including the one you notice until Wednesday.  We have changed the calls a
bit to have more meaning-full urls.

Στις Πέμ, 5 Μαΐ 2016 στις 1:25 π.μ., ο/η Rizart Dokollari <
notifications@github.com> έγραψε:
